project_id = "kpxdglccqxkudlasexki"

[functions.create-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-pix-notification]
verify_jwt = false

[functions.check-certificate]
verify_jwt = false

[functions.recover-abandoned-carts]
verify_jwt = false
